@startuml
hide footbox
actor User
participant ":TravelTrio" as TravelTrio
participant ":Ui" as Ui
participant ":CommandProcessor" as CommandProcessor
participant ":SetBudgetCommand" as SetBudgetCommand
participant ":BudgetList" as BudgetList
participant ":Activity" as Activity
participant ":Budget" as Budget

User -> TravelTrio : enter "setbudget"
TravelTrio -> CommandProcessor : process("setbudget")

CommandProcessor -> CommandProcessor : ensureTripOpen()
CommandProcessor -> Ui : showMessage(activity list)
Ui --> CommandProcessor : (activity selection acknowledge)
CommandProcessor -> Ui : promptInt("Enter the number of the activity to add a budget for.")
Ui --> CommandProcessor : activityIndex
CommandProcessor -> Ui : promptField("Is this amount in foreign currency? (y/n)")
Ui --> CommandProcessor : currencyChoice
CommandProcessor -> Ui : promptDouble("Enter budget amount ($)")
Ui --> CommandProcessor : budgetAmount

create SetBudgetCommand
CommandProcessor -> SetBudgetCommand : new SetBudgetCommand(openTrip.getBudgets(), openTrip.getActivities(), selectedActivity, budgetAmount, isForeign)
CommandProcessor -> SetBudgetCommand : execute()

SetBudgetCommand -> SetBudgetCommand : validate activity != null

SetBudgetCommand -> SetBudgetCommand : if isForeign, budgetAmount *= exchangeRate

create Budget
SetBudgetCommand -> Budget : new Budget(budgetAmount, selectedActivity)
Budget --> SetBudgetCommand : return newBudget

SetBudgetCommand -> BudgetList : addBudget(selectedActivity, newBudget)
BudgetList -> BudgetList : if existing budget -> adjust totalTripBudget
BudgetList -> BudgetList : budgets.put(activity, newBudget)
BudgetList -> BudgetList : totalTripBudget += newBudget.getActivityBudget()

SetBudgetCommand --> CommandProcessor : "Added budget for ..."
CommandProcessor -> Ui : showMessage(message)

destroy SetBudgetCommand

@enduml
