@startuml
hide footbox
participant ":SetCurrencyCommand" as SetCurrencyCommand
participant "budgetList:BudgetList" as BudgetList

-> SetCurrencyCommand : execute()
activate SetCurrencyCommand

opt exchangeRate > 0
    SetCurrencyCommand -> BudgetList : setExchangeRate(exchangeRate)
    activate BudgetList
    BudgetList --> SetCurrencyCommand
    deactivate BudgetList
end

<-- SetCurrencyCommand : result message
deactivate SetCurrencyCommand
@enduml
